---

- name: Install nomad
  hosts: nomad
  become: true
  tasks:
    - name: Install gpg
      ansible.builtin.apt:
        name: gpg, coreutils
        state: present

    - name: Download keyring
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /usr/share/keyrings/hashicorp-archive-keyring.asc

    - name: Configure repository
      ansible.builtin.apt_repository:
        filename: hashicorp
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        update_cache: yes
        state: present

    - name: Install nomad, consul, volt
      ansible.builtin.apt:
        name: nomad, consul, vault
        update_cache: yes
        state: present
#
#    - name: Set server config
#      ansible.builtin.replace:
#        path: /etc/zabbix/zabbix_agent2.conf
#        regexp: "^Server=127.0.0.1$"
#        replace: "Server={{ zabbix_host }}"
#      notify: Restart zabbix
#
#    - name: Set server active config
#      ansible.builtin.replace:
#        path: /etc/zabbix/zabbix_agent2.conf
#        regexp: "^ServerActive=127.0.0.1$"
#        replace: "ServerActive={{ zabbix_host }}"
#      notify: Restart zabbix
#
#    - name: Set hostname config
#      ansible.builtin.replace:
#        path: /etc/zabbix/zabbix_agent2.conf
#        regexp: "^Hostname=Zabbix server$"
#        replace: "Hostname={{ansible_host}}"
#      notify: Restart zabbix
#
    - name: Enable nomad service
      ansible.builtin.service:
        name: nomad
        enabled: true
        state: started

  handlers:
    - name: Nomad zabbix
      ansible.builtin.service:
        name: nomad
        state: restarted
