- name: Download Tailscale GPG Key
  ansible.builtin.uri:
    url: https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg

- name: Add Tailscale repository
  ansible.builtin.uri:
    url: https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list
    dest: /etc/apt/sources.list.d/tailscale.list

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    update_cache: true
    state: present

- name: Create bash completion directory
  ansible.builtin.file:
    path: /etc/bash_completion.d
    state: directory
    group: root
    owner: root

- name: Configure completion
  ansible.builtin.shell:
    cmd: tailscale completion bash > /etc/bash_completion.d/tailscale
    creates: /etc/bash_completion.d/tailscale
